spring:
  application:
    name: myapp
  thymeleaf:
    prefix: /WEB-INF/views/
    suffix: .html
  datasource:
    url: jdbc:postgresql://localhost:5432/e-learning
    username: root
    password: 123

server:
  port: 8096

#cors:
#  allowed-origins: "*"
#  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
#  allowed-headers: "*"
#  exposed-headers: "*"
